name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Only triggers on version tags like v1.0.0

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Adjust if needed

      - name: Install build tools
        run: |
          pip install --upgrade build

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
